# Generated by Django 6.0.3 on 2026-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InverterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ac_voltage', models.FloatField(null=True)),
                ('ac_frequency', models.FloatField(null=True)),
                ('pv_voltage', models.FloatField(null=True)),
                ('battery_voltage', models.FloatField(null=True)),
                ('battery_soc', models.IntegerField(null=True)),
                ('battery_charge_current', models.FloatField(null=True)),
                ('battery_discharge_current', models.FloatField(null=True)),
                ('load_voltage', models.FloatField(null=True)),
                ('load_frequency', models.FloatField(null=True)),
                ('load_power', models.IntegerField(null=True)),
                ('load_va', models.IntegerField(null=True)),
                ('load_percent', models.IntegerField(null=True)),
                ('output_source_priority', models.IntegerField(null=True)),
                ('charger_source_priority', models.IntegerField(null=True)),
                ('max_utility_charge_current', models.IntegerField(null=True)),
                ('charger_status', models.IntegerField(null=True)),
                ('connected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
