# Generated by Django 6.0.3 on 2026-04-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('metric_source', models.CharField(choices=[('solax', 'Solax Inverter'), ('battery', 'Battery BMS'), ('powmr', 'PowMr Inverter')], default='solax', max_length=20)),
                ('metric_name', models.CharField(help_text='Prometheus metric name, e.g. solax_feedin_power_watts', max_length=200)),
                ('metric_labels', models.JSONField(blank=True, default=dict, help_text='Label filters as JSON, e.g. {"inverter": "garage"}')),
                ('operator', models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or equal'), ('<', 'Less than'), ('<=', 'Less than or equal'), ('==', 'Equal'), ('!=', 'Not equal')], default='>', max_length=2)),
                ('threshold', models.FloatField(help_text='Numeric threshold to compare against')),
                ('duration_seconds', models.IntegerField(default=0, help_text='How long the condition must be true before firing (seconds)')),
                ('action_register', models.CharField(help_text='PowMr register name to write, e.g. output_source_priority', max_length=100)),
                ('action_value', models.IntegerField(help_text='Value to write to the register')),
                ('reset_register', models.CharField(blank=True, default='', max_length=100)),
                ('reset_value', models.IntegerField(blank=True, null=True)),
                ('reset_duration_seconds', models.IntegerField(default=0, help_text='How long condition must be false before resetting')),
                ('condition_met_since', models.DateTimeField(blank=True, null=True)),
                ('condition_clear_since', models.DateTimeField(blank=True, null=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('triggered', 'Triggered'), ('reset', 'Reset'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('metric_value', models.FloatField(null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
